version: 2

build:
  image: latest   

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py

python:
   version: 3.8
   install:
      - requirements: docs/requirements.txt